question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.",
     "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", 
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "A group of crows is called a murder.", "answer": "True"},
    {"text": "Goldfish have a memory span of three seconds.", "answer": "False"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "Humans share 98 percentage of their DNA with chimpanzees.", "answer": "True"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "Camels have three sets of eyelids to protect themselves from blowing sand.", "answer": "True"},
    {"text": "An octopus has three hearts.", "answer": "True"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "Humans can distinguish between over a trillion different smells.", "answer": "True"},
    {"text": "Venus is the closest planet to Earth.", "answer": "False"},
    {"text": "Humans have five senses.", "answer": "False"},
    {"text": "An ostrich's eye is bigger than its brain.", "answer": "True"},
    {"text": "There are more stars in the universe than grains of sand on Earth.", "answer": "True"},
    {"text": "A jiffy is an actual unit of time.", "answer": "True"},
    {"text": "Adult humans have 206 bones.", "answer": "True"},
    {"text": "The Earth is closer to the sun in the summer.", "answer": "False"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
    {"text": "An apple a day keeps the doctor away.", "answer": "False"},
    {"text": "Water makes up about 70 percentage of the human body.", "answer": "True"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "There is no gravity in space.", "answer": "False"},
    {"text": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"text": "Walt Disney was the creator of Mickey Mouse.", "answer": "True"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "A sneeze is faster than the blink of an eye.", "answer": "True"},
    {"text": "The shortest war in history lasted 38 minutes.", "answer": "True"},
    {"text": "The moon is made of cheese.", "answer": "False"},
    {"text": "Dolphins sleep with one eye open.", "answer": "True"},
    {"text": "Chameleons change color to blend into their surroundings.", "answer": "False"},
    {"text": "Polar bear fur is white.", "answer": "False"},
    {"text": "Bees can only sting once.", "answer": "False"},
    {"text": "A snail can sleep for three years.", "answer": "True"},
    {"text": "Koalas are bears.", "answer": "False"},
    {"text": "The Eiffel Tower can grow more than six inches during summer.", "answer": "True"},
    {"text": "Lightning is hotter than the surface of the sun.", "answer": "True"},
    {"text": "Humans and dinosaurs coexisted.", "answer": "False"},
    {"text": "Peanuts are nuts.", "answer": "False"},
    {"text": "The shortest complete sentence in the English language is 'Go.'", "answer": "True"},
    {"text": "There are more fake flamingos in the world than real ones.", "answer": "True"},
    {"text": "Jellyfish have brains.", "answer": "False"}
]